### PR TITLE
Install nc command

### PR DESCRIPTION
**Pull request by djui**

### CODE REVIEW

**Comment by pwaller** [comment]
[Travis failed](https://travis-ci.org/scraperwiki/hanoverd/builds/132186527#L930):

```
E: Unable to locate package netcat-openbsd
2016/05/23 05:38:31 Container run failed: The command '/bin/sh -c apt-get install -y netcat-openbsd' returned a non-zero code: 100
```

**Comment by pwaller** [comment]
I'm slightly curious why this ever worked before…

**Comment by djui** [comment]
First I thought, because one of the Dockerfiles only specifies `FROM Ubuntu` (while the other `FROM Ubuntu: 14.04`) there was a package with that name at some point in time available. But that seems not to be correct.

**Comment by djui** [comment]
Let me know if you want me to fix it.

**Comment by pwaller** [comment]
Not urgent. If/when you get a moment. Not a disaster if it gets dropped and picked up later.

**Comment by pwaller** [comment]
Superseded by #95 I guess?

**Pull request closed without merging**
