### PR TITLE
added hanoverdweb early

### PR DESCRIPTION
**Pull request by danigulyas**
Hi Peter!

I created another branch and did that origin-pointing stuff, how its looking now?

### CODE REVIEW

**Comment by pwaller** [comment]
Hi @danigulyas ! Sorry it took me a while to get around to this.

Thanks for doing the rebase before. There is one more piece of administration I need to ask of you. Would you mind signing your commit so that it's recorded that you agree to contribute the code, and improving the commit message? In particular it should start with a capital letter.

I've made a contributing document which hopefully makes it clear. If you have any problems don't hesit

https://github.com/scraperwiki/hanoverd/blob/master/CONTRIBUTING.md

I'll be sure to reply quickly next time. I'm keen to start building something with this.

**Comment by pwaller** [comment]
Hi @danigulyas, sorry we never followed up on this. At the moment we haven't had a need for a web interface in hanoverd, and I suspect we'll do it outside. I still would love it to be possible to use your code at some point in the future, so if you want to follow up on this, we can start another pull request. I'm closing this one for now. Don't worry if you don't have time, this project is a slow burn over here, since we're not actively developing it beyond bugfixes for the features we already have.

If you do make a new pull request, since the code is really separate from hanoverd, can we put it in `/contrib/web/`?

Thanks again!

**Comment by danigulyas** [comment]
Hi Peter!

Put it in, no problem!:)
Sorry for the late-anwser, im really busy theese days, im in the search of
a new job.

Regards,
-Dani

2015-07-22 12:44 GMT+02:00 Peter Waller <notifications@github.com>:

**Comment by pwaller** [comment]
No worries, best of luck with the search!

**Comment by danigulyas** [comment]
Thanks, most-likely im going to move from Hungary to Netherlands :) thats a
really big and exciting thing for me, i hope everything go well
Peter Waller <notifications@github.com> (időpont: 2015. júl. 23., Cs,
11:12) ezt írta:

**Pull request closed without merging**
